# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f608ad46c12af0575dea34e236018616612597ea0a3e968cf8566e402a637d0b67ada36cfadbfd3d3b14587b997b12abdd71e88151c8ebb26067c730219280f9

test:
  secret_key_base: fb389a6634ae2f111939f10eaab008ba6032a249836b3a816dcfe5ac439f22f5798f61472f195cefe074cb7e2a87b9356800c11dc074267bbada267043fabf12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
